export const SCHOOLS = [
  { id: 'foundations', name: 'AI Foundations', icon: '🧠', color: 'from-blue-500 to-cyan-500' },
  { id: 'automation', name: 'AI Automation', icon: '⚡', color: 'from-brand-500 to-yellow-500' },
  { id: 'business', name: 'AI for Business', icon: '🏢', color: 'from-forest-500 to-teal-500' },
  { id: 'creator', name: 'AI Creator & Income', icon: '💰', color: 'from-purple-500 to-pink-500' },
  { id: 'builder', name: 'AI Builder', icon: '🔧', color: 'from-red-500 to-orange-500' },
  { id: 'career', name: 'AI Career', icon: '🎯', color: 'from-indigo-500 to-blue-500' },
  { id: 'community', name: 'Community & Mentorship', icon: '🌍', color: 'from-earth-500 to-amber-500' },
]

export const SAMPLE_COURSES = [
  /* ═══════════════════════════════════════════════════════════════════
     🧠  SCHOOL 1 — AI FOUNDATIONS  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'AI for Complete Beginners in Africa',
    slug: 'ai-beginners-africa',
    description: 'Start your AI journey from zero. No technical background needed. Learn what AI is, how it works, and how to use it in your daily life and work.',
    school: 'foundations',
    category: 'AI Basics',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 180,
    enrolledCount: 4521,
    rating: 4.8,
    reviewCount: 312,
    tags: ['AI basics', 'beginner', 'no-code', 'Africa'],
    toolsCovered: ['ChatGPT', 'Claude', 'Gemini'],
    outcomes: [
      'Understand what AI is and how it works',
      'Use ChatGPT and Claude for work and study',
      'Apply AI in your business or career',
      'Build confidence using AI tools daily',
    ],
    africanFocused: true,
  },
  {
    title: 'Prompt Engineering Masterclass',
    slug: 'prompt-engineering-masterclass',
    description: 'Write prompts that get 10x better results from ChatGPT, Claude, and Gemini. Learn chaining, system prompts, few-shot patterns, and output control.',
    school: 'foundations',
    category: 'Prompt Engineering',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 210,
    enrolledCount: 5834,
    rating: 4.9,
    reviewCount: 421,
    tags: ['prompts', 'ChatGPT', 'Claude', 'productivity'],
    toolsCovered: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity'],
    outcomes: [
      'Write precise prompts that get exactly the output you need',
      'Use chain-of-thought and few-shot prompting techniques',
      'Create reusable prompt templates for work tasks',
      'Control output format — JSON, markdown, tables, code',
    ],
    africanFocused: true,
  },
  {
    title: 'Understanding Large Language Models (LLMs)',
    slug: 'understanding-llms',
    description: 'How do GPT-4, Claude, Gemini, and Llama actually work? Demystify transformers, tokens, temperature, context windows, and fine-tuning — no maths needed.',
    school: 'foundations',
    category: 'AI Concepts',
    level: 'intermediate',
    isFree: false,
    isPremium: false,
    price: 29,
    duration: 240,
    enrolledCount: 1876,
    rating: 4.7,
    reviewCount: 145,
    tags: ['LLMs', 'GPT', 'transformers', 'theory'],
    toolsCovered: ['ChatGPT', 'Claude', 'Hugging Face', 'Ollama'],
    outcomes: [
      'Explain how LLMs generate text in plain English',
      'Choose the right model for each use case',
      'Understand tokens, temperature, and context windows',
      'Run open-source models locally with Ollama',
    ],
    africanFocused: false,
  },
  {
    title: 'AI Image Generation — From DALL-E to Midjourney',
    slug: 'ai-image-generation',
    description: 'Create stunning visuals with AI. Master DALL-E 3, Midjourney, Stable Diffusion, and Leonardo AI for marketing, social media, and product design.',
    school: 'foundations',
    category: 'AI Images',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 200,
    enrolledCount: 3245,
    rating: 4.8,
    reviewCount: 267,
    tags: ['DALL-E', 'Midjourney', 'images', 'design'],
    toolsCovered: ['DALL-E 3', 'Midjourney', 'Leonardo AI', 'Canva AI'],
    outcomes: [
      'Generate professional images for any business need',
      'Write image prompts that produce consistent brand visuals',
      'Edit and upscale AI images for print and web',
      'Create product mockups, logos, and social media graphics',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Video & Voice — Create Content that Talks',
    slug: 'ai-video-voice-creation',
    description: 'Turn text into professional videos, clone your voice for podcasts, generate voiceovers, and build AI avatar presentations — no camera needed.',
    school: 'foundations',
    category: 'AI Video',
    level: 'beginner',
    isFree: false,
    isPremium: true,
    price: 49,
    duration: 260,
    enrolledCount: 2102,
    rating: 4.7,
    reviewCount: 178,
    tags: ['video', 'voice', 'HeyGen', 'ElevenLabs'],
    toolsCovered: ['HeyGen', 'ElevenLabs', 'Runway ML', 'Descript'],
    outcomes: [
      'Create AI avatar videos in any language',
      'Clone your voice for podcasts and narration',
      'Build faceless YouTube / TikTok content',
      'Generate voiceovers for ads and presentations',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Ethics, Safety & Responsible Use',
    slug: 'ai-ethics-safety',
    description: 'Navigate AI bias, misinformation, privacy, and copyright. Essential for anyone building or deploying AI — especially in African contexts.',
    school: 'foundations',
    category: 'Ethics',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 150,
    enrolledCount: 1340,
    rating: 4.6,
    reviewCount: 89,
    tags: ['ethics', 'safety', 'bias', 'regulation'],
    toolsCovered: ['ChatGPT', 'Claude', 'Google AI Principles'],
    outcomes: [
      'Identify AI bias and misinformation risks',
      'Apply responsible AI practices in your work',
      'Understand African AI regulation landscape',
      'Build AI systems that are fair and transparent',
    ],
    africanFocused: true,
  },
  {
    title: 'AI-Powered Research & Analysis',
    slug: 'ai-powered-research',
    description: 'Use AI to research topics in minutes, summarise papers, extract data from documents, and build knowledge bases. Perfect for students, consultants, and analysts.',
    school: 'foundations',
    category: 'Research',
    level: 'intermediate',
    isFree: false,
    isPremium: false,
    price: 39,
    duration: 220,
    enrolledCount: 1590,
    rating: 4.8,
    reviewCount: 132,
    tags: ['research', 'analysis', 'Perplexity', 'NotebookLM'],
    toolsCovered: ['Perplexity', 'NotebookLM', 'Claude', 'ChatGPT'],
    outcomes: [
      'Research any topic 10x faster with AI tools',
      'Summarise long documents and reports in seconds',
      'Extract structured data from PDFs and websites',
      'Build personal knowledge bases with NotebookLM',
    ],
    africanFocused: false,
  },

  /* ═══════════════════════════════════════════════════════════════════
     ⚡  SCHOOL 2 — AI AUTOMATION  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'No-Code Automation with Zapier & Make',
    slug: 'no-code-automation-zapier-make',
    description: 'Build powerful business automations without writing a single line of code. Connect your apps, automate repetitive tasks, and save hours every week.',
    school: 'automation',
    category: 'Automation',
    level: 'beginner',
    isFree: false,
    isPremium: true,
    price: 49,
    duration: 320,
    enrolledCount: 2841,
    rating: 4.9,
    reviewCount: 198,
    tags: ['Zapier', 'Make', 'automation', 'no-code'],
    toolsCovered: ['Zapier', 'Make', 'Airtable', 'Google Sheets'],
    outcomes: [
      'Build 10+ real-world automations',
      'Connect 100s of apps without code',
      'Automate WhatsApp, email, and social media',
      'Save 10+ hours per week for your business',
    ],
    africanFocused: true,
  },
  {
    title: 'WhatsApp Business Automation Masterclass',
    slug: 'whatsapp-business-automation',
    description: 'Automate your WhatsApp business messages, customer support, lead capture, and follow-ups. The #1 messaging tool in Africa, now fully automated.',
    school: 'automation',
    category: 'WhatsApp',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 240,
    enrolledCount: 3102,
    rating: 4.9,
    reviewCount: 287,
    tags: ['WhatsApp', 'automation', 'customer service', 'SME'],
    toolsCovered: ['WhatsApp Business API', 'Make', 'Twilio', 'Manychat'],
    outcomes: [
      'Set up automated WhatsApp responses 24/7',
      'Build a lead capture bot for your business',
      'Automate order confirmations and follow-ups',
      'Handle 100+ customer queries automatically',
    ],
    africanFocused: true,
  },
  {
    title: 'n8n Automation — Open-Source Power',
    slug: 'n8n-automation-open-source',
    description: 'Master n8n, the open-source automation platform. Build complex workflows, connect AI APIs, and self-host for free — no vendor lock-in.',
    school: 'automation',
    category: 'Automation',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 59,
    duration: 360,
    enrolledCount: 1678,
    rating: 4.8,
    reviewCount: 142,
    tags: ['n8n', 'open-source', 'self-hosted', 'workflows'],
    toolsCovered: ['n8n', 'OpenAI API', 'PostgreSQL', 'Docker'],
    outcomes: [
      'Build and deploy n8n workflows from scratch',
      'Connect AI models (GPT-4o, Claude) to n8n',
      'Self-host n8n on a $5/month VPS',
      'Build AI agents with n8n tool-use nodes',
    ],
    africanFocused: false,
  },
  {
    title: 'Email Marketing Automation with AI',
    slug: 'email-marketing-automation-ai',
    description: 'Build automated email sequences that write themselves. AI generates subject lines, body copy, and sends at the perfect time — on autopilot.',
    school: 'automation',
    category: 'Email Marketing',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 39,
    duration: 200,
    enrolledCount: 2345,
    rating: 4.7,
    reviewCount: 189,
    tags: ['email', 'marketing', 'Mailchimp', 'automation'],
    toolsCovered: ['Mailchimp', 'Brevo', 'ChatGPT', 'Zapier'],
    outcomes: [
      'Build a 7-email welcome sequence with AI-written copy',
      'Automate abandoned cart and re-engagement emails',
      'A/B test subject lines generated by AI',
      'Grow your email list with automated lead magnets',
    ],
    africanFocused: true,
  },
  {
    title: 'CRM & Sales Pipeline Automation',
    slug: 'crm-sales-pipeline-automation',
    description: 'Automate your entire sales pipeline — from lead capture to deal close. Connect forms, CRMs, invoicing, and follow-ups into one seamless system.',
    school: 'automation',
    category: 'Sales',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 69,
    duration: 340,
    enrolledCount: 1245,
    rating: 4.7,
    reviewCount: 108,
    tags: ['CRM', 'sales', 'Airtable', 'HubSpot'],
    toolsCovered: ['Airtable', 'HubSpot', 'Make', 'Google Forms'],
    outcomes: [
      'Build a complete CRM in Airtable for $0',
      'Automate lead scoring and qualification',
      'Set up automated proposal and invoice generation',
      'Track sales metrics in a real-time dashboard',
    ],
    africanFocused: true,
  },
  {
    title: 'Inventory & Operations Automation',
    slug: 'inventory-operations-automation',
    description: 'Automate stock tracking, reorder alerts, supplier communication, and delivery notifications. Built for African retailers, distributors, and e-commerce.',
    school: 'automation',
    category: 'Operations',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 180,
    enrolledCount: 1867,
    rating: 4.8,
    reviewCount: 154,
    tags: ['inventory', 'operations', 'retail', 'e-commerce'],
    toolsCovered: ['Google Sheets', 'Make', 'WhatsApp API', 'Airtable'],
    outcomes: [
      'Build automated low-stock alerts via WhatsApp',
      'Create real-time inventory dashboards',
      'Automate supplier purchase order emails',
      'Track deliveries with automated status updates',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Chatbot Builder — Zero to Production',
    slug: 'ai-chatbot-builder',
    description: 'Build AI-powered chatbots for customer support, lead generation, and internal tools. Deploy to WhatsApp, websites, and Telegram — no coding required.',
    school: 'automation',
    category: 'Chatbots',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 59,
    duration: 300,
    enrolledCount: 2090,
    rating: 4.9,
    reviewCount: 215,
    tags: ['chatbot', 'GPT', 'RAG', 'customer service'],
    toolsCovered: ['n8n', 'OpenAI API', 'Supabase', 'Voiceflow'],
    outcomes: [
      'Build a RAG chatbot trained on your business data',
      'Deploy chatbots to WhatsApp, web, and Telegram',
      'Handle 90% of customer queries automatically',
      'Implement human handoff for complex issues',
    ],
    africanFocused: true,
  },

  /* ═══════════════════════════════════════════════════════════════════
     🏢  SCHOOL 3 — AI FOR BUSINESS  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'AI for African SMEs — Grow Faster, Work Smarter',
    slug: 'ai-for-african-smes',
    description: 'Practical AI strategies for small and medium businesses in Africa. Cut costs, increase sales, and compete with bigger players using AI tools.',
    school: 'business',
    category: 'Business Strategy',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 45,
    duration: 290,
    enrolledCount: 2234,
    rating: 4.8,
    reviewCount: 203,
    tags: ['SME', 'business', 'Africa', 'productivity'],
    toolsCovered: ['ChatGPT', 'Notion AI', 'Google Workspace', 'Canva AI'],
    outcomes: [
      'Automate customer communication',
      'Create marketing content 10x faster',
      'Use AI for inventory and finance tracking',
      'Build an AI-powered customer service system',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Marketing & Content Strategy',
    slug: 'ai-marketing-content-strategy',
    description: 'Plan, create, and distribute marketing content using AI. From SEO blog posts to social media calendars — build a content machine for your brand.',
    school: 'business',
    category: 'Marketing',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 39,
    duration: 250,
    enrolledCount: 2890,
    rating: 4.8,
    reviewCount: 234,
    tags: ['marketing', 'content', 'SEO', 'social media'],
    toolsCovered: ['ChatGPT', 'Jasper', 'Canva AI', 'Buffer'],
    outcomes: [
      'Create a 30-day content calendar in 1 hour',
      'Write SEO-optimised blog posts with AI',
      'Generate social media captions for 5 platforms',
      'Build a brand voice guide that AI follows consistently',
    ],
    africanFocused: true,
  },
  {
    title: 'AI-Powered Finance & Bookkeeping',
    slug: 'ai-finance-bookkeeping',
    description: 'Automate invoicing, expense tracking, financial reporting, and tax prep using AI tools. Save your accountant 20 hours a month.',
    school: 'business',
    category: 'Finance',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 59,
    duration: 280,
    enrolledCount: 1456,
    rating: 4.7,
    reviewCount: 121,
    tags: ['finance', 'invoicing', 'bookkeeping', 'Paystack'],
    toolsCovered: ['Google Sheets', 'Wave', 'Zapier', 'Paystack'],
    outcomes: [
      'Auto-generate and send invoices on every sale',
      'Build real-time financial dashboards',
      'Automate expense categorisation with AI',
      'Generate monthly P&L reports automatically',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for Customer Service & Support',
    slug: 'ai-customer-service-support',
    description: 'Build a world-class customer support system using AI. Auto-respond to queries, route tickets, analyse sentiment, and reduce response time by 90%.',
    school: 'business',
    category: 'Customer Service',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 200,
    enrolledCount: 2123,
    rating: 4.8,
    reviewCount: 187,
    tags: ['customer service', 'support', 'chatbot', 'WhatsApp'],
    toolsCovered: ['WhatsApp API', 'Freshdesk', 'ChatGPT', 'Make'],
    outcomes: [
      'Reduce customer response time from hours to seconds',
      'Build an AI FAQ bot that handles 80% of queries',
      'Set up ticket routing and escalation automation',
      'Track customer satisfaction with AI sentiment analysis',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for Human Resources & Recruitment',
    slug: 'ai-hr-recruitment',
    description: 'Screen CVs with AI, automate interview scheduling, onboard new hires, and build employee self-service bots. HR automation for African companies.',
    school: 'business',
    category: 'HR',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 55,
    duration: 300,
    enrolledCount: 987,
    rating: 4.6,
    reviewCount: 78,
    tags: ['HR', 'recruitment', 'screening', 'onboarding'],
    toolsCovered: ['Claude API', 'Airtable', 'Make', 'Calendly'],
    outcomes: [
      'Build an AI CV screening pipeline that saves 10+ hours per role',
      'Automate interview scheduling and reminders',
      'Create AI-powered employee onboarding sequences',
      'Generate job descriptions and offer letters with AI',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for E-Commerce & Online Stores',
    slug: 'ai-ecommerce-online-stores',
    description: 'Use AI to write product descriptions, optimise pricing, automate order processing, and personalise customer experiences for your online store.',
    school: 'business',
    category: 'E-Commerce',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 45,
    duration: 260,
    enrolledCount: 1789,
    rating: 4.7,
    reviewCount: 156,
    tags: ['e-commerce', 'Shopify', 'product', 'pricing'],
    toolsCovered: ['ChatGPT', 'Shopify', 'Canva AI', 'Zapier'],
    outcomes: [
      'Generate compelling product descriptions at scale',
      'Automate order confirmation and shipping notifications',
      'Build personalised product recommendation emails',
      'Create AI-generated product images and mockups',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for Real Estate Professionals',
    slug: 'ai-real-estate-professionals',
    description: 'Automate property listings, lead follow-ups, virtual tours, and market analysis. AI tools built for African real estate agents and developers.',
    school: 'business',
    category: 'Real Estate',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 45,
    duration: 220,
    enrolledCount: 1234,
    rating: 4.7,
    reviewCount: 98,
    tags: ['real estate', 'property', 'listings', 'lead generation'],
    toolsCovered: ['ChatGPT', 'Canva AI', 'Make', 'Google Maps API'],
    outcomes: [
      'Auto-generate property listing descriptions',
      'Build automated lead follow-up sequences',
      'Create virtual tour presentations with AI',
      'Analyse local market trends using AI research tools',
    ],
    africanFocused: true,
  },

  /* ═══════════════════════════════════════════════════════════════════
     💰  SCHOOL 4 — AI CREATOR & INCOME  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'Build and Sell AI Services in Africa',
    slug: 'build-sell-ai-services-africa',
    description: 'Turn your AI skills into a real income stream. Learn to package, price, and sell AI services to businesses across Africa and globally.',
    school: 'creator',
    category: 'Freelancing',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 79,
    duration: 420,
    enrolledCount: 1923,
    rating: 4.7,
    reviewCount: 156,
    tags: ['freelancing', 'AI agency', 'income', 'business'],
    toolsCovered: ['ChatGPT', 'Claude', 'Canva AI', 'n8n'],
    outcomes: [
      'Launch your own AI service business',
      'Land your first 3 clients in 30 days',
      'Price your services confidently',
      'Build recurring income from AI consulting',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Content Creator — YouTube, TikTok & Podcasts',
    slug: 'ai-content-creator-social',
    description: 'Build a content empire using AI. Script videos, generate thumbnails, create podcasts, and grow your audience across YouTube, TikTok, and Instagram.',
    school: 'creator',
    category: 'Content Creation',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 45,
    duration: 280,
    enrolledCount: 3456,
    rating: 4.8,
    reviewCount: 289,
    tags: ['YouTube', 'TikTok', 'podcasts', 'content'],
    toolsCovered: ['ChatGPT', 'HeyGen', 'ElevenLabs', 'Canva AI'],
    outcomes: [
      'Script and produce YouTube videos 5x faster',
      'Create faceless TikTok content with AI avatars',
      'Launch an AI-powered podcast with cloned voice',
      'Generate thumbnails and social clips automatically',
    ],
    africanFocused: true,
  },
  {
    title: 'Start an AI Automation Agency',
    slug: 'start-ai-automation-agency',
    description: 'Blueprint for launching a profitable AI automation agency. Find clients, build systems, deliver results, and scale to $10K/month — step by step.',
    school: 'creator',
    category: 'Agency',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 99,
    duration: 480,
    enrolledCount: 1567,
    rating: 4.9,
    reviewCount: 198,
    tags: ['agency', 'business', 'automation', 'clients'],
    toolsCovered: ['n8n', 'Make', 'Zapier', 'Stripe'],
    outcomes: [
      'Set up your agency brand, website, and portfolio',
      'Build 5 productised automation packages to sell',
      'Land clients via LinkedIn, referrals, and cold outreach',
      'Deliver, manage, and scale client projects profitably',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Copywriting — Write Anything with AI',
    slug: 'ai-copywriting-write-anything',
    description: 'Master AI-assisted copywriting. Write sales pages, emails, ad copy, social posts, and blog articles — using ChatGPT and Claude as your writing partner.',
    school: 'creator',
    category: 'Writing',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 200,
    enrolledCount: 2678,
    rating: 4.7,
    reviewCount: 212,
    tags: ['copywriting', 'sales', 'emails', 'ads'],
    toolsCovered: ['ChatGPT', 'Claude', 'Jasper', 'Copy.ai'],
    outcomes: [
      'Write high-converting sales pages with AI',
      'Generate email sequences that nurture and sell',
      'Create Facebook and Google ad copy in minutes',
      'Develop a consistent brand voice with AI prompts',
    ],
    africanFocused: true,
  },
  {
    title: 'Sell AI-Generated Digital Products',
    slug: 'sell-ai-digital-products',
    description: 'Create and sell templates, e-books, courses, planners, and design assets — all generated with AI. Build a passive income stream from digital products.',
    school: 'creator',
    category: 'Digital Products',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 39,
    duration: 220,
    enrolledCount: 2145,
    rating: 4.6,
    reviewCount: 167,
    tags: ['digital products', 'templates', 'e-books', 'passive income'],
    toolsCovered: ['ChatGPT', 'Canva AI', 'Gumroad', 'Notion'],
    outcomes: [
      'Create 10 types of digital products with AI',
      'Set up a Gumroad or Selar storefront',
      'Price and market your products effectively',
      'Build a passive income funnel with email automation',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for Graphic Design & Branding',
    slug: 'ai-graphic-design-branding',
    description: 'Design logos, brand kits, social media graphics, and marketing materials using AI. No design experience needed — just describe what you want.',
    school: 'creator',
    category: 'Design',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 35,
    duration: 190,
    enrolledCount: 1987,
    rating: 4.7,
    reviewCount: 145,
    tags: ['design', 'branding', 'logos', 'Canva'],
    toolsCovered: ['Canva AI', 'DALL-E 3', 'Adobe Firefly', 'Looka'],
    outcomes: [
      'Design a complete brand kit with AI tools',
      'Create social media templates for every platform',
      'Generate logo concepts and iterate with AI',
      'Build a design portfolio to attract clients',
    ],
    africanFocused: true,
  },
  {
    title: 'Monetise AI on Fiverr & Upwork',
    slug: 'monetise-ai-fiverr-upwork',
    description: 'Learn exactly how to sell AI services on Fiverr, Upwork, and freelance platforms. Set up gigs, optimise profiles, and win your first 10 orders.',
    school: 'creator',
    category: 'Freelancing',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 160,
    enrolledCount: 4321,
    rating: 4.8,
    reviewCount: 356,
    tags: ['Fiverr', 'Upwork', 'freelancing', 'gigs'],
    toolsCovered: ['ChatGPT', 'Canva AI', 'Fiverr', 'Upwork'],
    outcomes: [
      'Set up high-converting Fiverr and Upwork profiles',
      'Create 5 AI-powered gig listings that attract buyers',
      'Deliver orders efficiently using AI workflows',
      'Scale to $1,000+/month in freelance AI income',
    ],
    africanFocused: true,
  },

  /* ═══════════════════════════════════════════════════════════════════
     🔧  SCHOOL 5 — AI BUILDER  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'Python for AI Automation',
    slug: 'python-ai-automation',
    description: 'Learn Python specifically for AI automation. Build scripts, connect APIs, create chatbots, and automate complex workflows — all with Python.',
    school: 'builder',
    category: 'Programming',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 89,
    duration: 540,
    enrolledCount: 1456,
    rating: 4.6,
    reviewCount: 134,
    tags: ['Python', 'programming', 'APIs', 'automation'],
    toolsCovered: ['Python', 'OpenAI API', 'LangChain', 'FastAPI'],
    outcomes: [
      'Write Python scripts for automation',
      'Connect to AI APIs (OpenAI, Anthropic)',
      'Build custom chatbots and agents',
      'Deploy AI apps to production',
    ],
    africanFocused: false,
  },
  {
    title: 'Build AI Agents with LangChain & CrewAI',
    slug: 'build-ai-agents-langchain-crewai',
    description: 'Build autonomous AI agents that plan, reason, and use tools. Master LangChain, CrewAI, and the agent pattern — the most in-demand AI skill of 2026.',
    school: 'builder',
    category: 'AI Agents',
    level: 'advanced',
    isFree: false,
    isPremium: true,
    price: 99,
    duration: 600,
    enrolledCount: 1123,
    rating: 4.8,
    reviewCount: 96,
    tags: ['agents', 'LangChain', 'CrewAI', 'autonomous'],
    toolsCovered: ['LangChain', 'CrewAI', 'OpenAI API', 'Python'],
    outcomes: [
      'Build multi-tool AI agents from scratch',
      'Implement ReAct, tool-use, and planning patterns',
      'Create multi-agent systems with CrewAI',
      'Deploy production-ready agents with memory and logging',
    ],
    africanFocused: false,
  },
  {
    title: 'RAG Systems — Build AI with Your Own Data',
    slug: 'rag-systems-build-ai-own-data',
    description: 'Build Retrieval-Augmented Generation systems. Upload your documents, create embeddings, and query them with AI — the foundation of every custom AI product.',
    school: 'builder',
    category: 'RAG',
    level: 'advanced',
    isFree: false,
    isPremium: true,
    price: 89,
    duration: 480,
    enrolledCount: 876,
    rating: 4.7,
    reviewCount: 72,
    tags: ['RAG', 'embeddings', 'vector database', 'Pinecone'],
    toolsCovered: ['LangChain', 'Pinecone', 'Supabase', 'OpenAI Embeddings'],
    outcomes: [
      'Build a complete RAG pipeline from scratch',
      'Chunk, embed, and store documents in vector databases',
      'Implement hybrid search (semantic + keyword)',
      'Evaluate and improve RAG accuracy',
    ],
    africanFocused: false,
  },
  {
    title: 'Build Full-Stack AI Apps with Next.js',
    slug: 'fullstack-ai-apps-nextjs',
    description: 'Build and deploy complete AI web applications. User auth, AI API integration, databases, real-time chat, and payments — all with Next.js and TypeScript.',
    school: 'builder',
    category: 'Web Development',
    level: 'advanced',
    isFree: false,
    isPremium: true,
    price: 99,
    duration: 720,
    enrolledCount: 945,
    rating: 4.8,
    reviewCount: 87,
    tags: ['Next.js', 'TypeScript', 'full-stack', 'deployment'],
    toolsCovered: ['Next.js', 'TypeScript', 'MongoDB', 'Vercel'],
    outcomes: [
      'Build production AI web apps end-to-end',
      'Integrate OpenAI and Anthropic APIs with streaming',
      'Implement user auth, payments, and dashboards',
      'Deploy to Vercel with CI/CD and monitoring',
    ],
    africanFocused: false,
  },
  {
    title: 'OpenAI & Anthropic API Deep Dive',
    slug: 'openai-anthropic-api-deep-dive',
    description: 'Master the OpenAI and Anthropic APIs. Structured outputs, function calling, vision, streaming, fine-tuning, and cost optimisation — everything you need.',
    school: 'builder',
    category: 'APIs',
    level: 'intermediate',
    isFree: false,
    isPremium: false,
    price: 69,
    duration: 400,
    enrolledCount: 1345,
    rating: 4.8,
    reviewCount: 118,
    tags: ['OpenAI', 'Anthropic', 'API', 'function calling'],
    toolsCovered: ['OpenAI API', 'Anthropic API', 'Python', 'Node.js'],
    outcomes: [
      'Use every OpenAI and Anthropic API feature',
      'Implement function calling and tool use',
      'Build streaming chat interfaces',
      'Optimise token usage and reduce costs by 60%',
    ],
    africanFocused: false,
  },
  {
    title: 'Build Custom GPTs & AI Assistants',
    slug: 'build-custom-gpts-assistants',
    description: 'Create custom GPTs in the OpenAI store and build AI assistants with the Assistants API. Retrieval, code interpreter, and function calling included.',
    school: 'builder',
    category: 'Custom GPTs',
    level: 'intermediate',
    isFree: false,
    isPremium: false,
    price: 49,
    duration: 260,
    enrolledCount: 2234,
    rating: 4.7,
    reviewCount: 189,
    tags: ['custom GPT', 'assistants', 'OpenAI', 'no-code'],
    toolsCovered: ['OpenAI GPT Builder', 'Assistants API', 'Python'],
    outcomes: [
      'Build and publish custom GPTs in the GPT Store',
      'Use the Assistants API with retrieval and code interpreter',
      'Create domain-specific AI assistants for any industry',
      'Monetise your custom GPTs with usage-based pricing',
    ],
    africanFocused: false,
  },
  {
    title: 'Deploy AI to Production — DevOps for AI',
    slug: 'deploy-ai-production-devops',
    description: 'Take your AI projects from localhost to production. Docker, CI/CD, monitoring, scaling, and cost management — everything you need to ship AI apps.',
    school: 'builder',
    category: 'DevOps',
    level: 'advanced',
    isFree: false,
    isPremium: true,
    price: 79,
    duration: 420,
    enrolledCount: 678,
    rating: 4.6,
    reviewCount: 54,
    tags: ['DevOps', 'Docker', 'deployment', 'production'],
    toolsCovered: ['Docker', 'Vercel', 'Railway', 'GitHub Actions'],
    outcomes: [
      'Containerise AI apps with Docker',
      'Set up CI/CD pipelines with GitHub Actions',
      'Monitor AI app performance and costs',
      'Scale from 0 to 10,000 users reliably',
    ],
    africanFocused: false,
  },

  /* ═══════════════════════════════════════════════════════════════════
     🎯  SCHOOL 6 — AI CAREER  (7 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'AI-Ready CV & LinkedIn Optimisation',
    slug: 'ai-ready-cv-linkedin',
    description: 'Build an AI-optimised CV and LinkedIn profile that gets interviews. Use AI to tailor applications, write cover letters, and stand out to recruiters.',
    school: 'career',
    category: 'Job Search',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 150,
    enrolledCount: 5678,
    rating: 4.9,
    reviewCount: 456,
    tags: ['CV', 'LinkedIn', 'job search', 'career'],
    toolsCovered: ['ChatGPT', 'Claude', 'LinkedIn', 'Canva'],
    outcomes: [
      'Build an ATS-friendly CV that passes screening',
      'Optimise your LinkedIn for AI and tech roles',
      'Generate tailored cover letters for each application',
      'Build a portfolio that showcases your AI skills',
    ],
    africanFocused: true,
  },
  {
    title: 'Land a Remote AI Job from Africa',
    slug: 'land-remote-ai-job-africa',
    description: 'Your complete guide to landing remote AI and tech jobs from anywhere in Africa. Job boards, networking, interviewing, and salary negotiation.',
    school: 'career',
    category: 'Remote Work',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 39,
    duration: 200,
    enrolledCount: 3456,
    rating: 4.8,
    reviewCount: 287,
    tags: ['remote work', 'jobs', 'Africa', 'career'],
    toolsCovered: ['LinkedIn', 'ChatGPT', 'Loom', 'Notion'],
    outcomes: [
      'Find and apply to 50+ remote AI job listings',
      'Ace technical and behavioural interviews with AI prep',
      'Negotiate salaries and benefits confidently',
      'Set up your remote work environment for success',
    ],
    africanFocused: true,
  },
  {
    title: 'AI Product Manager — Break Into PM',
    slug: 'ai-product-manager',
    description: 'Transition into AI Product Management. Learn to define AI product requirements, work with ML teams, and build product roadmaps for AI features.',
    school: 'career',
    category: 'Product Management',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 69,
    duration: 360,
    enrolledCount: 876,
    rating: 4.7,
    reviewCount: 67,
    tags: ['product management', 'PM', 'AI products', 'career'],
    toolsCovered: ['Notion', 'Figma', 'ChatGPT', 'Linear'],
    outcomes: [
      'Write AI product requirements and user stories',
      'Evaluate AI/ML feasibility for product features',
      'Build and present AI product roadmaps',
      'Prepare for AI PM interviews at top companies',
    ],
    africanFocused: false,
  },
  {
    title: 'AI Data Analyst — From Zero to Hired',
    slug: 'ai-data-analyst-zero-to-hired',
    description: 'Become an AI-powered data analyst. Use Python, SQL, and AI tools to analyse data, build dashboards, and tell stories that drive business decisions.',
    school: 'career',
    category: 'Data Analysis',
    level: 'intermediate',
    isFree: false,
    isPremium: true,
    price: 79,
    duration: 480,
    enrolledCount: 1234,
    rating: 4.8,
    reviewCount: 98,
    tags: ['data analysis', 'Python', 'SQL', 'dashboards'],
    toolsCovered: ['Python', 'Pandas', 'SQL', 'Power BI'],
    outcomes: [
      'Analyse datasets with Python and Pandas',
      'Write SQL queries for business intelligence',
      'Build interactive dashboards with Power BI',
      'Use AI to automate data cleaning and reporting',
    ],
    africanFocused: true,
  },
  {
    title: 'Ace the AI Technical Interview',
    slug: 'ace-ai-technical-interview',
    description: 'Prepare for AI and ML engineering interviews. Coding challenges, system design, ML concepts, and behavioural questions — with AI-assisted practice.',
    school: 'career',
    category: 'Interview Prep',
    level: 'advanced',
    isFree: false,
    isPremium: true,
    price: 59,
    duration: 300,
    enrolledCount: 654,
    rating: 4.7,
    reviewCount: 45,
    tags: ['interviews', 'coding', 'system design', 'ML'],
    toolsCovered: ['Python', 'ChatGPT', 'LeetCode', 'System Design'],
    outcomes: [
      'Solve common AI/ML interview coding problems',
      'Design AI systems at scale (system design rounds)',
      'Explain ML concepts clearly for non-technical rounds',
      'Build a portfolio that impresses hiring managers',
    ],
    africanFocused: false,
  },
  {
    title: 'AI for Teachers & Educators',
    slug: 'ai-for-teachers-educators',
    description: 'Transform your teaching with AI. Create lesson plans, grade assignments, generate quizzes, and provide personalised feedback — all with AI tools.',
    school: 'career',
    category: 'Education',
    level: 'beginner',
    isFree: false,
    isPremium: false,
    price: 29,
    duration: 180,
    enrolledCount: 1876,
    rating: 4.8,
    reviewCount: 156,
    tags: ['education', 'teaching', 'lesson plans', 'grading'],
    toolsCovered: ['ChatGPT', 'Claude', 'Canva AI', 'Quillbot'],
    outcomes: [
      'Generate lesson plans and worksheets in minutes',
      'Create AI-powered quizzes and assessments',
      'Provide personalised feedback at scale',
      'Build interactive learning materials with AI',
    ],
    africanFocused: true,
  },
  {
    title: 'Transition to Tech — AI Career Switch',
    slug: 'transition-to-tech-ai-career',
    description: 'Switch from any career into AI and tech. Whether you are in banking, law, healthcare, or education — map your existing skills to AI roles.',
    school: 'career',
    category: 'Career Switch',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 180,
    enrolledCount: 4123,
    rating: 4.8,
    reviewCount: 334,
    tags: ['career switch', 'tech', 'transition', 'skills'],
    toolsCovered: ['ChatGPT', 'LinkedIn', 'GitHub', 'Notion'],
    outcomes: [
      'Map your current skills to AI industry roles',
      'Build a 90-day career transition plan',
      'Create a project portfolio from scratch',
      'Network effectively in the African tech ecosystem',
    ],
    africanFocused: true,
  },

  /* ═══════════════════════════════════════════════════════════════════
     🌍  SCHOOL 7 — COMMUNITY & MENTORSHIP  (4 courses)
     ═══════════════════════════════════════════════════════════════════ */
  {
    title: 'AI Community Leadership',
    slug: 'ai-community-leadership',
    description: 'Learn how to build and lead AI communities in Africa. Organise meetups, run workshops, grow online groups, and create impact at scale.',
    school: 'community',
    category: 'Leadership',
    level: 'intermediate',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 160,
    enrolledCount: 987,
    rating: 4.7,
    reviewCount: 67,
    tags: ['community', 'leadership', 'meetups', 'workshops'],
    toolsCovered: ['Notion', 'Discord', 'Luma', 'ChatGPT'],
    outcomes: [
      'Start and grow an AI community from zero',
      'Organise engaging workshops and meetups',
      'Build an online presence for your community',
      'Create mentorship programs that deliver results',
    ],
    africanFocused: true,
  },
  {
    title: 'Teach AI — Become an AfriFlow Instructor',
    slug: 'teach-ai-become-instructor',
    description: 'Want to teach on AfriFlow AI? This course teaches you how to create courses, record content, engage students, and earn income as an AI educator.',
    school: 'community',
    category: 'Teaching',
    level: 'intermediate',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 140,
    enrolledCount: 567,
    rating: 4.6,
    reviewCount: 34,
    tags: ['teaching', 'instructor', 'course creation', 'income'],
    toolsCovered: ['Loom', 'Canva AI', 'ChatGPT', 'OBS Studio'],
    outcomes: [
      'Structure and outline an engaging AI course',
      'Record professional-quality video lessons',
      'Create supplementary materials with AI',
      'Launch your course and earn your first revenue',
    ],
    africanFocused: true,
  },
  {
    title: 'AI for Social Impact in Africa',
    slug: 'ai-social-impact-africa',
    description: 'Apply AI to solve real African challenges — healthcare access, agricultural productivity, financial inclusion, education, and climate resilience.',
    school: 'community',
    category: 'Social Impact',
    level: 'beginner',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 200,
    enrolledCount: 1345,
    rating: 4.9,
    reviewCount: 112,
    tags: ['social impact', 'Africa', 'healthcare', 'agriculture'],
    toolsCovered: ['ChatGPT', 'Python', 'TensorFlow', 'Hugging Face'],
    outcomes: [
      'Identify AI opportunities in healthcare, agriculture, and finance',
      'Build a social impact AI project proposal',
      'Use open-source AI tools for resource-limited settings',
      'Apply for AI for Good grants and funding',
    ],
    africanFocused: true,
  },
  {
    title: 'Open-Source AI — Contribute & Collaborate',
    slug: 'open-source-ai-contribute',
    description: 'Join the global open-source AI movement. Learn to use, contribute to, and build with Hugging Face, LLaMA, Stable Diffusion, and other open models.',
    school: 'community',
    category: 'Open Source',
    level: 'intermediate',
    isFree: true,
    isPremium: false,
    price: 0,
    duration: 220,
    enrolledCount: 678,
    rating: 4.6,
    reviewCount: 45,
    tags: ['open source', 'Hugging Face', 'LLaMA', 'GitHub'],
    toolsCovered: ['Hugging Face', 'Git', 'Python', 'Ollama'],
    outcomes: [
      'Navigate and use Hugging Face models and datasets',
      'Run open-source LLMs locally on your machine',
      'Make your first contribution to an AI open-source project',
      'Fine-tune open models for African languages and contexts',
    ],
    africanFocused: true,
  },
]

export const AFRICAN_COUNTRIES = [
  'Ghana', 'Nigeria', 'Kenya', 'South Africa', 'Rwanda', 'Ethiopia',
  'Tanzania', 'Uganda', 'Senegal', 'Ivory Coast', 'Cameroon', 'Egypt',
  'Morocco', 'Tunisia', 'Zimbabwe', 'Zambia', 'Botswana', 'Namibia',
  'Other'
]

export const TRANSFORMATION_PATHS = [
  {
    title: 'From beginner to AI-ready worker',
    duration: '30 days',
    icon: '🚀',
    steps: ['AI Foundations', 'Prompt Engineering', 'AI for Productivity', 'Portfolio Project'],
    audience: 'Fresh graduates & job seekers',
  },
  {
    title: 'From unemployed to AI freelancer',
    duration: '60 days',
    icon: '💼',
    steps: ['AI Basics', 'Automation Tools', 'Service Packaging', 'First Client'],
    audience: 'Youth & recent graduates',
  },
  {
    title: 'From SME owner to automated business',
    duration: '21 days',
    icon: '🏪',
    steps: ['AI for Business', 'WhatsApp Automation', 'Customer Service Bot', 'Go Live'],
    audience: 'Business owners',
  },
  {
    title: 'From marketer to AI consultant',
    duration: '45 days',
    icon: '📈',
    steps: ['AI Marketing Tools', 'Content Automation', 'Analytics & AI', 'Consulting Setup'],
    audience: 'Marketing professionals',
  },
]
